version: '3'
services:
  todoapp-redis:
    container_name: todoapp_redis
    image: redis
    restart: always
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"

  db:
    container_name: todoapp_postgres
    image: postgres
    restart: always
    volumes:
      - todoapp_db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  todoapp:
    container_name: todoapp
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - todoapp-redis

  todoapp-nginx:
    container_name: todoapp_nginx
    image: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - todoapp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy.conf:/etc/nginx/proxy.conf

volumes:
  todoapp_db: